### ISSUE TITLE
flutter get pub

### ISSUE THREAD

**Issue by NesaByte** [BetaPundit/Yoga-Guru#8]
Hey there! 
Happy Hacktoberfest!

This is a super awesome project. I just started learning dart and I am extremely interested in how pose estimation works. I found your project and thought we should add the `flutter get pub` command in running the app in your README.md.

`flutter get pub` command gets all the dependencies listed in the pubspec.yaml file in the current working directory, as well as their transitive dependencies.

**Comment by BetaPundit** [comment]
That's really great.
Thanks!
